### PR TITLE
Add tox. Prove Python 3.6 support

### PR DESCRIPTION
**Pull request by rklyne**

### CODE REVIEW

**Comment by datenhahn** [comment]
Sorry for the late response, I was busy the last months. I ran tox and it seems the imgcompare code yields different results on python 2 vs. 3. The tests fail on python 3.6 as they don't yield the exact numbers expected. Probably it still works good enough, but I will investigate the reasons.

Did the tests run through for you?

**Comment by rklyne** [comment]
No worries - we're all working for free here :)

The tests did pass for me when I added tox support. I will run them again and report back.

**Comment by rklyne** [comment]
They are failing now. There are slight increases in the diff percentages.

**Comment by rklyne** [comment]
It passes with `Pillow~=6.1.0` which was the latest when I made this PR. It fails as you saw with `Pillow==7.0.0`

**Comment by datenhahn** [comment]
Yes, when I pin Pillow in setup.py it works again:  install_requires=['pillow==6.2.2']

also with python 3

**Comment by rklyne** [comment]
Yeah, Python 2 only installs Pillow 6.2.2. Pillow 7.0.0 changes behaviour and drops Python 2 support.

We could:
1. Constrain the dependency: `Pillow<7.0.0`
2. Change the tests to accept different results on later Pillow versions

What's your preferred way forward?

**Comment by datenhahn** [comment]
I don't have an immediate idea how to fix that. I don't want to pin the Pillow version, as I don't want to prevent people from upgrading Pillow, but also I would like to have repeatable results. Changing the tests also came to my mind, but that would basically be cheating.

I think there are only two solutions:
* Pin Pillow to be < 7.0.0
* Find out what was changed in Pillow, maybe some function param or legacy compatibility function/setting can be used

I will investigate this a bit further and keep you updated.

**Comment by datenhahn** [comment]
A little update:
* I added some disclaimer info on the master Readme meanwhile (albeit "major changes" might have been a bit exagerated in the new light of things)
* I think I found the code snippet where it goes wrong. I added some debug output and traced it down to the `diff.convert('L')`, these functions seem to yield different results between Pillow 6.2.2 and 7.0.0 . I can also see a commit with the message "Fix rounding error on RGB to L conversion" which changed between 6.2.2 and 7.0.0 which might change the output.

https://github.com/python-pillow/Pillow/commit/d68147ce8979b1da05884f98d5ba30d81ae0df2f

I did not have time yet to understand what that code actually does. I have planned these two next steps:
* understand what is happening in the conversion and what implications that change has on it
* compile Pillow 7.0.0 once with and once without the fix to see if the differences vanish when the fix is removed (this step might not be necessary. It might enough to understand what is going on)

**Comment by datenhahn** [comment]
In this *Recommendation ITU-R BT.601-7*

https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.601-7-201103-I!!PDF-E.pdf

On page 6 and 7 you find the formula and values to convert a RGB Signal into
a YCrCb signal. This formula is used in Pillow to transform a RGB value into
a Luminosity value only, so the final result is a greyscale image with the
information most significant for the human eye.

The formula for converting 16 Bit RGB values how described in the document is:

    LUMINOSITY = int(19595/2^16 * RED + 38470/2^16 * GREEN + 7471/2^16 * BLUE)

which also can be written as

    LUMINOSITY = int( (19595 * RED + 38470 * GREEN + 7471 * BLUE) / 2 ^ 16 )
	
which also can be implemented with bit shifting

    LUMINOSITY = int( (19595 * RED + 38470 * GREEN + 7471 * BLUE) >> 16 )

The Pillow 6.2.2 implementation was, the following, which looks correct on first
sight, but does not take rounding into account as the 16 least significant
bits are just cut off.

The SPEC says: The operator int( ) returns the value of 0 for fractional parts in the range of 0 to 0.4999 ... and +1 for fractional parts in the range 0.5 to 0.999 ..., i.e. it rounds up fractions above 0.5.

```c
#define L24(rgb)\
    ((rgb)[0]*19595 + (rgb)[1]*38470 + (rgb)[2]*7471)

static void
rgb2l(UINT8* out, const UINT8* in, int xsize)
{
    int x;
    for (x = 0; x < xsize; x++, in += 4)
        /* ITU-R Recommendation 601-2 (assuming nonlinear RGB) */
        *out++ = L24(in) >> 16;
}
```

So the following fix adds `0x8000`  or `32768' in decimal (half of 2^16 which is 65536) to the resulting
number before bitshifting. Which has the effect of tipping some numbers over to the next int
(rounding up fractions above 0.5) in the result after bitshifting.

```
#define L24(rgb)\
    ((rgb)[0]*19595 + (rgb)[1]*38470 + (rgb)[2]*7471 + 0x8000)
```

This means Pillow 6.2.2 indeed had a bug which was fixed in 7.0.0 . Which means for the imgcompare lib I am thinking about the following approach:

* Updating the Readme with some explanation
* Releasing a 1.0.0 version which has Pillow <= 6.2.2 as install requirement
* Releasing a 2.0.0 version which has Pillow >= 7.0.0 as install requirement
* Optional: offering a compatibility mode which implements the 6.2.2 conversion mode in pure python (will be slower and more memory intense, but might be useful for some), I don't think I will do this unless requested.

**Comment by datenhahn** [comment]
Thanks for your input, I added a tox.ini to the repo, but I used pyenv to setup the 4 different python3 versions

**Comment by rklyne** [comment]
Thank you!

**Pull request closed without merging**
